[program:security-test-center-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/security-test-center/artisan queue:work --sleep=1 --tries=1 --timeout=180
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/security-test-center/storage/logs/worker.log
stopwaitsecs=190
